Adding support for CMA-GFS in WPS
wrf-model/WPS pull request #236
Opened 2023-10-10 05:10 UTC by andrewsoong

The CMA-GFS grib2 datasets is now able to be ingested by the ungrib program. The GRAPES_GFS(here in after referred to as CMA_GFS), the new generation of Global/Regional Assimilation and Prediction Enhanced System which is independently developped by China Meteorological Administration (CMA), has been put into formal operation. So we are committed to solving the problem of WPS correctly handling CMA_GFS forecast data.

one Vtable files(Vtable.CMA_GFS) has been created with the fields required by the WRF model. 
Modifications to the ungrib source code: Adding support for code 738 in rd_grid2.F because model levels of CMA_GFS are on generalized vertical height coordinates. 

The CMA_GFS real time data is here:http://data.wis.cma.cn/DCPC_WMC_BJ/open/nwp/gmf_gra/

I've tested the program with an Intel compiler and it passed without errors. CMA_GFS forecast data were also used to test, the results are normal.

2024-05-10 18:44 UTC, jimbresch commented
A test of the modified code on a dataset pulled from that CMA web site segfaulted. I haven't found the cause, but note that CMA uses several vertical level types that aren't decoded by rd_grib2. Their files also cause problems for g2print. So, it will take debugging and mods to get it working.

I also suggest renaming Vtable.CMA_GFS to something else, since it may be confused with the NCEP GFS by some users. Vtable.CMA_GRAPES perhaps? Otherwise we may need to have a naming convention of the form Vtable.center_model and rename all the NCEP Vtables.

2024-05-10 19:25 UTC, jimbresch requested changes
ungrib failed on derecho. Some debugging and mods may be needed.

2024-05-11 02:28 UTC, andrewsoong commented
> A test of the modified code on a dataset pulled from that CMA web site segfaulted. I haven't found the cause, but note that CMA uses several vertical level types that aren't decoded by rd_grib2. Their files also cause problems for g2print. So, it will take debugging and mods to get it working.
> 
> I also suggest renaming Vtable.CMA_GFS to something else, since it may be confused with the NCEP GFS by some users. Vtable.CMA_GRAPES perhaps? Otherwise we may need to have a naming convention of the form Vtable.center_model and rename all the NCEP Vtables.

Hello, Jim.
The China Meteorological Administration(CMA) has changed its name from GRAPES_GFS to CMA_GFS.
To differentiate from NCEP GFS, it is necessary to remind users.
Do you now need to change Vtable.CMA_GFS to Vtable.CMA_GRAPES?
Also, I think we need to have a naming convention of the form Vtable.center_model.
Thanks !

2024-05-20 19:45 UTC, jimbresch commented
Hi Andrew,
OK, we'll keep the name as Vtable.CMA_GFS. The decoding is failing inside an NCEP g2 library routine. Do you have a dataset that has been successfully ungribbed with WPS? Every file that I've tested from the CMA web site is very large and has failed to be decoded. 
The date tag on your code modification is from 2018. If CMA increased the resolution of their GFS since then, it might explain the failure.

2024-05-21 00:43 UTC, andrewsoong commented
> Hi Andrew, OK, we'll keep the name as Vtable.CMA_GFS. The decoding is failing inside an NCEP g2 library routine. Do you have a dataset that has been successfully ungribbed with WPS? Every file that I've tested from the CMA web site is very large and has failed to be decoded. The date tag on your code modification is from 2018. If CMA increased the resolution of their GFS since then, it might explain the failure.

Hi,Jim,
I have just tested the latest CMA-GFS forecast data from：http://data.wis.cma.cn/DCPC_WMC_BJ/open/nwp/gmf_gra/t1200/f0_f240_6h/, WPS-V4.5 runs well, generated normal data. See: hsong_2024-05-21_8_09_45.txt for test information. My Linux platform is Rock Linux 9.2, and the Intel compiler version is 2021.10.0.
By the way, do you need me to mail you any data files for your tests? What's your e-mail address? Feel free to email me.
[hsong_2024-05-21_8_09_45.txt](https://github.com/wrf-model/WPS/files/15382886/hsong_2024-05-21_8_09_45.txt)

Haiqing Soong (宋海清)
Ph.D,  Associate Professor,
Ecological and Agricultural Meteorology Center of Inner Mongolia &
Inner Mongolia Meteorological Satellite Remote Sensing Center，
Building A, Inner Mongolia Meteorological Bureau, Hailaer Road,
Xincheng District, Hohhot, 010051,China
Tel: 0471-3335230
E-Mail: [haiqingsong2010@163.com](mailto:haiqingsong2010@163.com), and [haiqingsong@emails.imau.edu.cn](mailto:haiqingsong@emails.imau.edu.cn)

2024-06-14 02:07 UTC, andrewsoong commented
@jimbresch Do We need to resubmit this PR based on WPS-V4.6.0?

2024-06-14 15:04 UTC, weiwangncar commented
@andrewsoong You should be able to continue to amend this PR, unless you are addressing a different issue.

2024-12-17 14:24 UTC, andrewsoong commented
> Hi Andrew, OK, we'll keep the name as Vtable.CMA_GFS. The decoding is failing inside an NCEP g2 library routine. Do you have a dataset that has been successfully ungribbed with WPS? Every file that I've tested from the CMA web site is very large and has failed to be decoded. The date tag on your code modification is from 2018. If CMA increased the resolution of their GFS since then, it might explain the failure.

Have you solved your problem?

2024-12-22 00:34 UTC, jimbresch commented
The problem was due to incompatibility of the external libraries compiled with an older version of the compiler on derecho with a new re-compile of WPS.  The wrfhelp libraries don't work with a new compile. The problem was hard to track since ungrib fails on some grib2 files and not others. The CMA file was one which caused a failure. The fault is not with this PR.

2024-12-22 00:38 UTC, jimbresch approved these changes
These changes permit ungribbing of the CMA model output. Tests on derecho were successful. Note that the global CMA output files are very large and time-consuming to download.

2024-12-22 16:50 UTC, andrewsoong commented
> These changes permit ungribbing of the CMA model output. Tests on derecho were successful. Note that the global CMA output files are very large and time-consuming to download.

Thanks，Jim！

Dr. Wei Wang，Will these changes work correctly on the NCAR machine? Thanks！ @weiwangncar

2024-12-23 02:04 UTC, weiwangncar commented
@andrewsoong: @jimbresch has tested it on our HPC (Derecho), and it seems to work.

2024-12-23 04:30 UTC, andrewsoong commented
> @andrewsoong: @jimbresch has tested it on our HPC (Derecho), and it seems to work.

@weiwangncar Is the WRF team considering merging this capability in the next release?

2024-12-24 01:36 UTC, weiwangncar commented
@andrewsoong Yes, we are considering it.

2024-12-24 01:37 UTC, andrewsoong commented
> @andrewsoong Yes, we are considering it.

Thanks，Wei ！

2024-12-24 04:11 UTC, jimbresch commented
@andrewsoong   It would be helpful if you or CMA could provide documentation on the grib codes for the fields in the CMA model output files. Some of the fields seem to be non-standard or locally defined. While not needed for initializing WRF, the codes could be added to g2print.

2024-12-24 08:04 UTC, andrewsoong commented
> @andrewsoong It would be helpful if you or CMA could provide documentation on the grib codes for the fields in the CMA model output files. Some of the fields seem to be non-standard or locally defined. While not needed for initializing WRF, the codes could be added to g2print.

I am very sorry, I contacted CMA Technical Staff, but I did not get the relevant documentation.

2025-04-22 03:34 UTC, mgduda commented
@weiwangncar If you also approve this PR, I'll merge it to `develop` so the changes will appear in the WPS v4.7.0 release.

2025-04-22 03:38 UTC, weiwangncar approved these changes

2025-04-22 03:56 UTC, merged